site_name: TrajCenter
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
  - coverage:
      page_name: coverage        #URL : /coverage/
      html_report_dir: docs/coverage  # le rapport HTML

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

nav:
  - Accueil: index.md
  - Référence API:
    # --- AUTOGEN_API_START ---
    - Trajcenter:
      - Converter:
        - Base: api/trajcenter/converter/base.md
        - Column Mapper: api/trajcenter/converter/column_mapper.md
        - Defaults: api/trajcenter/converter/defaults.md
        - Excel Converter: api/trajcenter/converter/excel_converter.md
        - Mod Converter: api/trajcenter/converter/mod_converter.md
      - Core:
        - Trajectory: api/trajcenter/core/trajectory.md
# --- AUTOGEN_API_END ---
  - Coverage: coverage.md 

