# trajcenter/robot/abb/errors/__init__.py
"""Lightweight initializer for the robot/abb/errors package.

This file intentionally avoids eager public re-exports to prevent circular imports and expensive import side effects.

Generated by py-init-tools — do not edit manually.
"""

from __future__ import annotations

# No eager public re-exports

__all__ = [
]
