#!/usr/bin/env python3
# trajcenter/converter/mod_converter.py
"""Converter for ABB RAPID modules (``.mod``) to the ``.trajcenter`` format.

Author: Clement RACINET

A RAPID ``.mod`` file contains a procedure with ``MoveL``, ``MoveJ`` or
``MoveC`` instructions. Each instruction encodes an inline robtarget
with its movement parameters.

Expected Move line format
--------------------------
::

    MoveL [[x,y,z],[q1,q2,q3,q4],[cf1,cf4,cf6,cfx],[eax_a,…,eax_f]],
          speed, zone, ToolName \\wobj:=WobjName ;

Parsing rules
--------------
- Only lines whose first token starts with ``MoveL``, ``MoveJ`` or
  ``MoveC`` (case-insensitive) are processed.
- Physical lines are merged on the ``;`` delimiter before parsing,
  which handles robtargets formatted across multiple lines.
- Speed is a RAPID **variable name** (e.g. ``vitesse``) in files
  generated by CATIA. It is stored only when it is a recognised RAPID
  literal (e.g. ``v500``). Otherwise the ``speed`` column is
  autocompleted from
  :class:`~trajcenter.converter.defaults.ConversionDefaults`.
- Zone is stored as-is when it is a recognised RAPID literal
  (``fine`` or ``z<digits>``). When it is a variable name, a
  :class:`UserWarning` is emitted and the default zone is used.
- External axes equal to ``9E9`` are considered **inactive** and are
  not stored in the ``DataFrame`` (absent ``eax_*`` column = axis does
  not exist).
- Tools and wobjs are deduplicated and indexed in the
  ``Trajectory.tools`` and ``Trajectory.wobjs`` tables.
- All columns in
  :data:`~trajcenter.core.trajectory.CONVERTER_COLUMNS` are guaranteed
  to be present on output via
  :meth:`~trajcenter.converter.base.BaseConverter._autocomplete`.

Example:
    ::

        from pathlib import Path
        from trajcenter.converter.mod_converter import ModConverter
        from trajcenter.converter.defaults import ConversionDefaults

        # Conversion with standard defaults
        traj = ModConverter().convert(Path("trajectory_files/sphere05mm.mod"))
        print(traj)
        # Trajectory(name='sphere05mm', points=17, tools=1, wobjs=1, eax=none, complete=True)

        # Conversion with a custom fallback speed
        traj = ModConverter(
            defaults=ConversionDefaults(speed="v200")
        ).convert(Path("trajectory_files/sphere05mm.mod"))
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pandas as pd

from trajcenter.converter.base import BaseConverter
from trajcenter.converter.defaults import ConversionDefaults
from trajcenter.core.messages import msg
from trajcenter.core.trajectory import (
    MoveType,
    SourceFormat,
    Trajectory,
    TrajectoryMeta,
)


# ---------------------------------------------------------------------------
# Constants & regex
# ---------------------------------------------------------------------------

#: Captures the movement type at the start of a line (case-insensitive).
_RE_MOVE_TYPE: re.Pattern[str] = re.compile(r"^\s*(MoveL|MoveJ|MoveC)\b", re.IGNORECASE)

#: Captures the raw robtarget content:
#: ``[[x,y,z],[q1,q2,q3,q4],[cf1,cf4,cf6,cfx],[eax_a,…,eax_f]]``
#: Group 1 contains the four sub-lists without the outer brackets.
_RE_ROBTARGET: re.Pattern[str] = re.compile(
    r"\[\s*"  # opening [ of the robtarget
    r"(\[.*?\]"  # [x,y,z]
    r"\s*,\s*\[.*?\]"  # [q1,q2,q3,q4]
    r"\s*,\s*\[.*?\]"  # [cf1,cf4,cf6,cfx]
    r"\s*,\s*\[.*?\])"  # [eax_a…eax_f]
    r"\s*\]",  # closing ] of the robtarget
    re.DOTALL,
)

#: Captures speed, zone, tool and wobj after the last ``]]`` of the robtarget.
#: Zone accepts any RAPID identifier (fine, z10, or a variable name).
_RE_PARAMS: re.Pattern[str] = re.compile(
    r"\]\]\s*,"  # ]] closing the robtarget
    r"\s*(?P<speed>\S+?)\s*,"  # speed
    r"\s*(?P<zone>\w+)\s*,"  # zone (any RAPID identifier)
    r"\s*(?P<tool>\w+)"  # tool
    r"(?:\s*\\[Ww][Oo][Bb][Jj]\s*:=\s*(?P<wobj>\w+))?",  # \wobj:=WobjName (optional)
    re.IGNORECASE,
)

#: Recognised RAPID zone literals: ``fine`` or ``z`` followed by digits only.
_RE_ZONE_LITERAL: re.Pattern[str] = re.compile(r"^(?:fine|z\d+)$", re.IGNORECASE)

#: ABB sentinel value for an inactive external axis.
_EAX_INACTIVE: float = 9e9

#: Threshold below which an eax value is considered active.
#: (9E9 may drift slightly depending on the numeric formatter of the .mod file)
_EAX_ACTIVE_THRESHOLD: float = 1e8

#: External axis column names in RAPID robtarget order.
_EAX_COLS: list[str] = ["eax_a", "eax_b", "eax_c", "eax_d", "eax_e", "eax_f"]

#: Mapping of movement type (lowercase) → :class:`~trajcenter.core.trajectory.MoveType`.
_MOVE_TYPE_MAP: dict[str, MoveType] = {
    "movel": MoveType.MOVE_L,
    "movej": MoveType.MOVE_J,
    "movec": MoveType.MOVE_C,
}

#: Prefix of recognised RAPID speed literals (e.g. ``v500``, ``v1000``).
_RAPID_SPEED_PREFIX: str = "v"


# ---------------------------------------------------------------------------
# Converter
# ---------------------------------------------------------------------------


class ModConverter(BaseConverter):
    """Converter for ABB RAPID modules (``.mod``) to :class:`~trajcenter.core.trajectory.Trajectory`.

    Parses all ``MoveL`` / ``MoveJ`` / ``MoveC`` instructions in a
    ``.mod`` file and builds a complete
    :class:`~trajcenter.core.trajectory.Trajectory` object with:

    - deduplicated tool and wobj tables;
    - all columns in
      :data:`~trajcenter.core.trajectory.CONVERTER_COLUMNS` guaranteed
      present (autocompleted via
      :attr:`~trajcenter.converter.base.BaseConverter.defaults`).

    Attributes:
        defaults: Default values for autocompletion (inherited from
            :class:`~trajcenter.converter.base.BaseConverter`).

    Example:
        ::

            from pathlib import Path
            from trajcenter.converter.mod_converter import ModConverter

            traj = ModConverter().convert(Path("trajectory_files/sphere05mm.mod"))
            traj.save("trajectory_store/sphere05mm.trajcenter")
    """

    def __init__(self, defaults: ConversionDefaults | None = None) -> None:
        """Initialise the RAPID converter.

        Args:
            defaults: Default values for autocompletion.
                When ``None``,
                :class:`~trajcenter.converter.defaults.ConversionDefaults`
                is instantiated with its own standard values.
        """
        super().__init__(defaults)

    def convert(self, source: Path) -> Trajectory:
        """Convert a RAPID ``.mod`` file to a :class:`~trajcenter.core.trajectory.Trajectory`.

        ABB Route:
            N/A — local file conversion, no RWS call.

        ABB Constraints:
            None.

        Args:
            source: Path to the ``.mod`` file to convert.

        Returns:
            A valid, complete, unsaved
            :class:`~trajcenter.core.trajectory.Trajectory` object.

        Raises:
            FileNotFoundError: If the source file does not exist.
            ValueError: If no Move instruction is found, or if parsing
                a line fails.

        Example:
            ::

                traj = ModConverter().convert(Path("trajectory_files/sphere05mm.mod"))
        """
        source = Path(source)
        if not source.exists():
            raise FileNotFoundError(msg("FILE_NOT_FOUND", path=source))

        raw_lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
        move_lines = self._extract_move_lines(raw_lines)

        if not move_lines:
            raise ValueError(msg("NO_MOVE_INSTRUCTION", path=source))

        rows, tools, wobjs = self._parse_move_lines(move_lines, source)

        df = pd.DataFrame(rows)
        df, autocompleted = self._autocomplete(df, tools, wobjs)

        meta = TrajectoryMeta(
            name=source.stem,
            source_file=source.name,
            source_format=SourceFormat.RAPID,
            autocompleted=autocompleted,
        )

        return Trajectory(meta=meta, points=df, tools=tools, wobjs=wobjs)

    # ------------------------------------------------------------------
    # Internal steps
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_move_lines(lines: list[str]) -> list[str]:
        """Filter and return only lines that contain a Move instruction.

        Strategy:
        - Tokens are accumulated in the buffer ONLY when they belong to
          a Move instruction (triggered by MoveL/MoveJ/MoveC).
        - Non-Move RAPID lines (MODULE, PROC, VAR, …) are ignored even
          when they do not contain a ``;``.
        - The buffer is flushed on ``;``.

        Args:
            lines: Raw lines from the ``.mod`` file.

        Returns:
            List of complete Move instructions, one per element.
        """
        result: list[str] = []
        buffer: str = ""
        in_move: bool = False

        for line in lines:
            stripped = line.strip()

            if not stripped or stripped.startswith("!"):
                continue

            if not in_move:
                if _RE_MOVE_TYPE.match(stripped):
                    in_move = True
                    buffer = stripped
                else:
                    continue
            else:
                buffer = buffer + " " + stripped

            if ";" in buffer:
                instruction, _, remainder = buffer.partition(";")
                instruction = instruction.strip()
                if instruction:
                    result.append(instruction)
                buffer = remainder.strip()
                in_move = bool(buffer) and bool(_RE_MOVE_TYPE.match(buffer))

        return result

    def _parse_move_lines(
        self,
        move_lines: list[str],
        source: Path,
    ) -> tuple[list[dict[str, str | int | float]], list[str], list[str]]:
        """Parse each Move line and build the data structures.

        Args:
            move_lines: Merged Move lines (one instruction per element).
            source: Path to the source file (used in error messages).

        Returns:
            Tuple ``(rows, tools, wobjs)`` where:

            - ``rows``: list of dicts, one per point.
            - ``tools``: ordered list of tool names (index → name).
            - ``wobjs``: ordered list of wobj names (index → name).

        Raises:
            ValueError: If the robtarget or parameters of a line cannot
                be parsed.
        """
        rows: list[dict[str, str | int | float]] = []
        tools_index: dict[str, int] = {}
        wobjs_index: dict[str, int] = {}

        for line_no, line in enumerate(move_lines, start=1):
            try:
                row = self._parse_single_move(line, tools_index, wobjs_index, line_no)
            except ValueError as exc:
                raise ValueError(
                    f"{source.name} — Move line #{line_no}: {exc}\n"
                    f"  Content: {line[:120]!r}"
                ) from exc
            rows.append(row)

        tools = _index_to_list(tools_index)
        wobjs = _index_to_list(wobjs_index)

        return rows, tools, wobjs

    def _parse_single_move(
        self,
        line: str,
        tools_index: dict[str, int],
        wobjs_index: dict[str, int],
        point_idx: int = 0,
    ) -> dict[str, str | int | float]:
        """Parse a single Move line and return a point dict.

        Updates ``tools_index`` and ``wobjs_index`` in place when new
        names are encountered.

        When the zone token is not a recognised RAPID literal
        (``fine`` or ``z<digits>``), a :class:`UserWarning` is emitted
        and the default zone from :attr:`defaults` is substituted.

        Args:
            line: Complete Move line (one instruction).
            tools_index: Mutable dict name → index (updated in place).
            wobjs_index: Mutable dict name → index (updated in place).
            point_idx: 0-based point index used in warning messages.

        Returns:
            Dict with keys: ``x, y, z, q1, q2, q3, q4``,
            ``cf1, cf4, cf6, cfx``, ``move_type``, ``zone``,
            ``tool_index``, ``wobj_index``,
            optionally ``speed`` (when a recognised RAPID literal) and
            ``eax_a``…``eax_f`` (active axes only).

        Raises:
            ValueError: If the robtarget or parameters cannot be
                extracted or converted.
        """
        # --- Movement type ---
        m_type = _RE_MOVE_TYPE.match(line)
        if not m_type:
            raise ValueError("Movement type not found.")
        move_type = _MOVE_TYPE_MAP[m_type.group(1).lower()]

        # --- Robtarget ---
        m_robt = _RE_ROBTARGET.search(line)
        if not m_robt:
            raise ValueError(
                msg("INSTRUCTION_WITHOUT_ROBTARGET", line=point_idx, content=line[:80])
            )

        # Extract the 4 sub-lists: [trans],[rot],[conf],[eax]
        sublists = re.findall(r"\[([^\[\]]+)\]", m_robt.group(1))
        if len(sublists) < 4:
            raise ValueError(
                f"Malformed robtarget — {len(sublists)} sub-list(s) found, 4 expected."
            )

        try:
            trans = [float(v) for v in sublists[0].split(",")]
            rot = [float(v) for v in sublists[1].split(",")]
            eax = [float(v) for v in sublists[3].split(",")]
        except ValueError as exc:
            raise ValueError(f"Numeric conversion failed in robtarget: {exc}") from exc

        # Confdata: may contain non-integer values → raise with dedicated message
        try:
            conf = [int(float(v)) for v in sublists[2].split(",")]
        except ValueError as exc:
            raise ValueError(
                msg("INVALID_CONFDATA", line=point_idx, content=sublists[2])
            ) from exc

        if len(trans) != 3:
            raise ValueError(f"trans must have 3 values, got {len(trans)}.")
        if len(rot) != 4:
            raise ValueError(f"rot must have 4 values, got {len(rot)}.")
        if len(conf) != 4:
            raise ValueError(f"conf must have 4 values, got {len(conf)}.")
        if len(eax) != 6:
            raise ValueError(f"eax must have 6 values, got {len(eax)}.")

        # --- Parameters (speed, zone, tool, wobj) ---
        m_params = _RE_PARAMS.search(line)
        if not m_params:
            raise ValueError("Move parameters (speed/zone/tool) not found.")

        speed_raw: str = m_params.group("speed")
        zone_raw: str = m_params.group("zone")
        tool_name: str = m_params.group("tool")
        wobj_name: str = m_params.group("wobj") or "wobj0"

        # --- Zone: warn and substitute default when not a RAPID literal ---
        if not _RE_ZONE_LITERAL.match(zone_raw):
            warnings.warn(
                msg("ZONE_VARIABLE_WARNING", zone=zone_raw, idx=point_idx),
                UserWarning,
                stacklevel=2,
            )
            zone_raw = self.defaults.zone

        # --- tool / wobj index ---
        if tool_name not in tools_index:
            tools_index[tool_name] = len(tools_index)
        if wobj_name not in wobjs_index:
            wobjs_index[wobj_name] = len(wobjs_index)

        # --- Point dict construction ---
        row: dict[str, str | int | float] = {
            "x": trans[0],
            "y": trans[1],
            "z": trans[2],
            "q1": rot[0],
            "q2": rot[1],
            "q3": rot[2],
            "q4": rot[3],
            "cf1": conf[0],
            "cf4": conf[1],
            "cf6": conf[2],
            "cfx": conf[3],
            "move_type": move_type.value,
            "zone": zone_raw,
            "tool_index": tools_index[tool_name],
            "wobj_index": wobjs_index[wobj_name],
        }

        # Speed: stored only when it is a RAPID literal (v500, v1000, …)
        # Otherwise absent → autocompleted from defaults in _autocomplete()
        if (
            speed_raw.lower().startswith(_RAPID_SPEED_PREFIX)
            and speed_raw[1:].isdigit()
        ):
            row["speed"] = speed_raw

        # External axes: stored only when active (value < 9E9 threshold)
        for col, val in zip(_EAX_COLS, eax):
            if abs(val) < _EAX_ACTIVE_THRESHOLD:
                row[col] = val

        return row


# ---------------------------------------------------------------------------
# Module-level utility
# ---------------------------------------------------------------------------


def _index_to_list(index: dict[str, int]) -> list[str]:
    """Convert a ``name → index`` dict to an ordered ``index → name`` list.

    Args:
        index: Dict mapping name → integer position (0-based, dense).

    Returns:
        List where ``result[i]`` is the name at index ``i``.

    Example:
        ::

            _index_to_list({"Tool_formage": 0, "tool0": 1})
            # → ["Tool_formage", "tool0"]
    """
    result: list[str] = [""] * len(index)
    for name, idx in index.items():
        result[idx] = name
    return result
