# trajcenter/rws/errors/__init__.py
"""Public re-exports for the TrajCenter RWS protocol error package.

> **Author**: Clément RACINET
"""

from __future__ import annotations

from trajcenter.rws.errors.base import (
    RAPID_STRMAX,
    TrajCenterAuthError,
    TrajCenterConflictError,
    TrajCenterError,
    TrajCenterForbiddenError,
    TrajCenterInternalError,
    TrajCenterNotFoundError,
    TrajCenterTimeoutError,
    TrajCenterUpstreamError,
    TrajCenterValidationError,
)
from trajcenter.rws.errors.codes import (
    ERROR_CODE_REGISTRY,
    ControllerTimeout,
    ControllerUnavailable,
    IncompatibleRobotState,
    InternalClientError,
    InvalidMoveCPair,
    InvalidMoveType,
    InvalidProcessParams,
    InvalidReadConfs,
    InvalidRobtarget,
    InvalidRWSResponse,
    InvalidTcpSpeed,
    InvalidTrajcenterFormat,
    InvalidZoneType,
    MastershipDeniedError,
    MissingTcpSpeedNoDefault,
    MissingToolNameNoDefault,
    MissingWobjNameNoDefault,
    MissingZoneTypeNoDefault,
    ProcessTypesNotFound,
    RapidSymbolNotFound,
    RobotDefaultNotFound,
    RWSAuthenticationRefused,
    RWSRequestTimeout,
    RWSWriteForbidden,
    SelectedTrajIndexOutOfBounds,
    SerializationError,
    ToolNameNotFoundOnRobot,
    TooManyPoints,
    TooManyProcessParamSets,
    TrajectoryConversionError,
    TrajectoryFileNotFound,
    TrajectoryStoreNotFound,
    TrajToolsNotFound,
    TrajWobjsNotFound,
    TransferAlreadyInProgress,
    TransferTimeout,
    UnknownProcessType,
    WobjNameNotFoundOnRobot,
)
from trajcenter.rws.errors.translate import from_rws_exception

__all__ = [
    "ERROR_CODE_REGISTRY",
    "RAPID_STRMAX",
    "ControllerTimeout",
    "ControllerUnavailable",
    "IncompatibleRobotState",
    "InternalClientError",
    "InvalidMoveCPair",
    "InvalidMoveType",
    "InvalidProcessParams",
    "InvalidRWSResponse",
    "InvalidReadConfs",
    "InvalidRobtarget",
    "InvalidTcpSpeed",
    "InvalidTrajcenterFormat",
    "InvalidZoneType",
    "MastershipDeniedError",
    "MissingTcpSpeedNoDefault",
    "MissingToolNameNoDefault",
    "MissingWobjNameNoDefault",
    "MissingZoneTypeNoDefault",
    "ProcessTypesNotFound",
    "RWSAuthenticationRefused",
    "RWSRequestTimeout",
    "RWSWriteForbidden",
    "RapidSymbolNotFound",
    "RobotDefaultNotFound",
    "SelectedTrajIndexOutOfBounds",
    "SerializationError",
    "TooManyPoints",
    "TooManyProcessParamSets",
    "ToolNameNotFoundOnRobot",
    "TrajCenterAuthError",
    "TrajCenterConflictError",
    "TrajCenterError",
    "TrajCenterForbiddenError",
    "TrajCenterInternalError",
    "TrajCenterNotFoundError",
    "TrajCenterTimeoutError",
    "TrajCenterUpstreamError",
    "TrajCenterValidationError",
    "TrajToolsNotFound",
    "TrajWobjsNotFound",
    "TrajectoryConversionError",
    "TrajectoryFileNotFound",
    "TrajectoryStoreNotFound",
    "TransferAlreadyInProgress",
    "TransferTimeout",
    "UnknownProcessType",
    "WobjNameNotFoundOnRobot",
    "from_rws_exception",
]
